<h1>CNN(Convolutional Neural Networks)</h1>

<h2>Stride</h2>

Stride controls how mnay pixels the filter moves at each step. Stride = 1 moves one pixel at a time (default), Stride = 2 moves two pixels - reduces output size by half

<h2>Padding</h2>

Withoud padding, the output is smaller than the input (edges are partially ignored). Padding='same' adds zeros the border so the ouput size equals the input size. Padding='valid' means no padding (ouput shrinks)

In [3]:
import numpy as np

image = np.array(
    [
        [0,0,0,1,1,1],
        [0,0,0,1,1,1],
        [0,0,0,1,1,1],
        [0,0,0,1,1,1],
        [0,0,0,1,1,1],
        [0,0,0,1,1,1]
    ]
)

kernel = np.array([
    [-1,0,1],
    [-1,0,1],
    [-1,0,1]
])

h,w = image.shape

kh,kw = kernel.shape

output_h = h-kh+1
output_w = w-kw+1

feature_map= np.zeros((output_h,output_w))

for i in range(output_h):
    for j in range(output_w):
        patch = image[i:i+kh,j:j+kw]
        feature_map[i,j] = np.sum(patch*kernel)

print(feature_map)

[[0. 3. 3. 0.]
 [0. 3. 3. 0.]
 [0. 3. 3. 0.]
 [0. 3. 3. 0.]]


In [8]:
from tensorflow.keras.layers import Conv2D

conv_layer = Conv2D(filters=32,kernel_size=3,strides=1,padding='same',activation='relu')